org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.218
neo_version_range=[21,)

loader_version_range=[4,)
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14

mod_id=slavic_delight
mod_name=Slavic Delight
mod_license=All Rights Reserved
mod_version=0.3.2

mod_group_id=com.legomanchik
mod_authors=LegoManchik, Barium56
mod_description=

jei_minecraft=1.21
jei_version=19.8.2.99
farmers_delight=6917256
